Fixing the native SDK versions to patch versions
rudderlabs/rudder-sdk-react-native pull request #118
Opened 2022-05-25 12:51 UTC by desusai7

## Fixing the native SDK versions to patch versions

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-05-25 13:08 UTC, pallabmaiti requested changes

2022-05-25 13:08 UTC, pallabmaiti commented on android/build.gradle
> +    implementation 'com.rudderstack.android.sdk:core:[1.5.1, 1.6.0)'
let's make it 1.9.9 instead of 1.6.0

2022-05-25 13:39 UTC, pallabmaiti submitted a review, later dismissed

2022-05-25 19:39 UTC, kekami commented
`RNRudderAnalytics.h` also need to be updated to resolve `'RSIntegrationFactory.h' file not found with <angled> include; use "quotes" instead`

```diff
- #import <RSIntegrationFactory.h">
+ #import "RSIntegrationFactory.h"
- #import <RSConfig.h>
+ #import "RSConfig.h"
```

2022-05-26 05:10 UTC, pallabmaiti submitted a review, later dismissed

2022-05-26 10:15 UTC, pallabmaiti approved these changes

2022-05-26 10:16 UTC, merged